{
 "title": "Application SLIs",
 "tags": [
  "observability-platform",
  "application"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_total[2m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_total{status=~\"5..\"}[2m])) / sum(rate(http_server_requests_total[2m]))) * 100",
     "legendFormat": "5xx error rate"
    }
   ]
  },
  {
   "title": "Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_seconds_bucket[3m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_seconds_bucket[3m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_seconds_bucket[3m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}