{
 "title": "Loki Log Explorer",
 "tags": [
  "observability-platform",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Log Volume by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({compose_project=\"observability-platform\"}[1m])) by (container)"
    }
   ]
  },
  {
   "title": "target-app logs (all)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"target-app\"}"
    }
   ]
  },
  {
   "title": "Errors across all containers",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{compose_project=\"observability-platform\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "webhook-receiver: alerts received",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"webhook-receiver\"} |= \"alert received\""
    }
   ]
  }
 ]
}